// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRNvUghwHW6PE3z_FOj8Hmvbx1KCOgu9U',
    appId: '1:929781444063:web:f2ab53030d4c265adae86a',
    messagingSenderId: '929781444063',
    projectId: 'nptypush',
    authDomain: 'nptypush.firebaseapp.com',
    storageBucket: 'nptypush.appspot.com',
    measurementId: 'G-X5EV3F0YX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhXff4bp9oC1Nd2VN2DBzfmJDnQdC4UQ',
    appId: '1:929781444063:android:c2eda7ea70826375dae86a',
    messagingSenderId: '929781444063',
    projectId: 'nptypush',
    storageBucket: 'nptypush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKKvWjx7D3mi0-g53TwBwvWEWR_tbwQmo',
    appId: '1:929781444063:ios:1eee8ba27f4eb4acdae86a',
    messagingSenderId: '929781444063',
    projectId: 'nptypush',
    storageBucket: 'nptypush.appspot.com',
    iosBundleId: 'com.example.nptypush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKKvWjx7D3mi0-g53TwBwvWEWR_tbwQmo',
    appId: '1:929781444063:ios:1eee8ba27f4eb4acdae86a',
    messagingSenderId: '929781444063',
    projectId: 'nptypush',
    storageBucket: 'nptypush.appspot.com',
    iosBundleId: 'com.example.nptypush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRNvUghwHW6PE3z_FOj8Hmvbx1KCOgu9U',
    appId: '1:929781444063:web:32d9f2d552caa94edae86a',
    messagingSenderId: '929781444063',
    projectId: 'nptypush',
    authDomain: 'nptypush.firebaseapp.com',
    storageBucket: 'nptypush.appspot.com',
    measurementId: 'G-RPCBT82G90',
  );

}